
Vagrant.configure("2") do |config|
  
  config.vm.box = "centos/7"
  config.vm.hostname = "control-node"
  config.vm.network "private_network", ip: '192.168.1.2' # rede interna que so vai esta disponivel para comunicação dentro do enviriment do virtualBox
  # nfs -> sistema de arquivo remoto
  config.vm.synced_folder ".", "/vagrant", type: "nfs"
  config.vm.provision "shell", path: "provision.sh"
end
