---
- name: Configurar servidor de aplicação Java
  hosts: app01

  user: vagrant
  become: yes

  vars:
    - dbhost: "db01"
    - dbname: "notes"
    - dbusername: "notesapp"
    - dbpassword: "root"
  
  tasks:
    - name: Configurar hosts lab ansible
      lineinfile:
        dest: /etc/hosts
        state: present
        line: "{{item}}" # recebe uma lista de item 
      with_items: # onde tem meus itens onde vai ser adicionado no etc/hosts
        - 192.168.1.2 contorle-node
        - 192.168.1.3 app01
        - 192.168.1.4 db01
    - name: Adicionar usuario de app
      user:
        name: app
        comment: Usuario de aplicação
        uid: 500
    - name: Instalação do Maven
      yum:
        name: maven
        state: latest
    - name: Instalação do java
      yum:
        name: java-1.8.0-openjdk
        state: latest
    - name: Criação do diretório de app
      file:
        path: /opt/notes
        state: directory
        owner: app
        group: app
    - name: instalação do git client # atividade 2
      yum:
        name: git
        state: latest
    - name: Clone do repositório Notes - app
      git:
        repo: 'https://github.com/callicoder/spring-boot-mysql-rest-api-tutorial.git'
        dest: /opt/notes
        clone: yes
        force: yes
    - name: Configurar arquivo de propriedades para camada de banco de dados
      template:
        src: application.properties
        dest: /opt/notes/src/main/resources/application.properties
    - name: Gerar pacote da aplicação
      command: mvn -f /opt/notes/pom.xml package
      become_user: app
    - name: Registrar versao autal do pacote
      shell:
        cmd: mvn -o -q -Dexec.executable=echo -Dexec.arg='${project.version}'
        chdir: /opt/notes/
      register: app_version
    - name: Configurar serviço do Systemd
      template:
        src: etc/systemd/system/notes.service
        src: /etc/systemd/system/notes.service
        notify: reload daemon
    - name: Iniciar serviço notes
      service:
        name: notes
        state: restarted
  roles:
    - configuracao-default-so
  handlers:
    - name: reload app
      systemd:
        state: restarted
        deamon_reload: yes
        name: 'notes'
    - name: reload daemon
      systemd:
        daemon_reexec: yes