--- #inicio do arquivo yaml
- name: Configurar servidor de banco de dados # nome do playbook
  hosts: db01 # maquina de banco de dados

  user: vagrant # usuario padrao criado pelo o vagrant
  become: yes # para executar como root
  vars_files: # diretorio de variaveis
    - vars/main.yaml
  vars: # variaveis dentro do yaml
    - dbname: "db01"
    - dbusername: "root"
    - dbpassword: "root"
  roles: # atividades que nao estao dentro das tasks
    - configuracao-default-so
    - role: geerlingguy.mysql
