mysql_root_password: devops
mysql_database:
  - name: notes
    encoding: latin1
    collation: latin1_general_ci
mysql_users:
  - name: notesapp
    host: "%" # qualquer hosts
    password: root
    priv: "notes.*:ALL"